id: a4383e84-ad92-4771-8f58-d0a459542be0
slug: calico-newrelic
title: Calico-Newrelic

description: |
  Calico is an open source networking and network security solution for containers, virtual machines, and native host-based workloads. Calico supports a broad range of platforms including Kubernetes, OpenShift, Mirantis Kubernetes Engine (MKE), OpenStack, and bare metal services.Whether you opt to use Calico's eBPF data plane or Linux’s standard networking pipeline, Calico delivers blazing fast performance with true cloud-native scalability

  Install this quickstart to access preconfigured Calico observability solutions based on Prometheus metrics that are available out-of-the-box

summary: |
   A curated dashboard based on Prometheus metrics which helps you understand the Calico CNI of your k8s cluster

# Support level: New Relic | Verified | Community (required)
level: Community

# Authors of the quickstart (required)
authors:
  - Ragalahari Potti

# Keywords for filtering / searching criteria in the UI
keywords:
  - calico
  - kubernetes
  - k8s
  - prometheus
  - remote-write

installPlans:
  - setup-prometheus

# Documentation references
documentation:
  - name: Prometheus Remote Write Configuration
    url: https://docs.newrelic.com/docs/infrastructure/prometheus-integrations/install-configure-remote-write/set-your-prometheus-remote-write-integration/
    description: Configure your Prometheus Server to remote write metrics to New Relic
  - name: Calico Metrics Documentation
    url: https://projectcalico.docs.tigera.io/reference/felix/prometheus
    description: Learn more about the Prometheus metrics available for Calico-felix

icon: logo.png
website: https://projectcalico.docs.tigera.io/

dashboards:
  - calico

alertPolicies:
  - calico
