name: Nginx-ingress config load errors alert

description: |+
  This alert is triggered when there is an error loading ingress configuration
type: STATIC
nrql:
  query: "FROM Metric SELECT IF(min(nginx_ingress_controller_config_last_reload_successful) < 1, 1, 0)"

# Function used to aggregate the NRQL query value(s) for comparison to the terms.threshold (Default: SINGLE_VALUE)
valueFunction: SINGLE_VALUE

# List of Critical and Warning thresholds for the condition
terms:
  - priority: CRITICAL
    # Operator used to compare against the threshold.
    operator: EQUALS
    # Value that triggers a violation
    threshold: 1
    # Time in seconds; 120 - 3600
    thresholdDuration: 300
    # How many data points must be in violation for the duration
    thresholdOccurrences: ALL

# Duration after which a violation automatically closes
# Time in seconds; 300 - 2592000 (Default: 86400 [1 day])
violationTimeLimitSeconds: 86400

