name: Ingress certificate expiration alert

description: |+
 This alert is triggered when there are less than 30 days remaining for certificate expiration. The alert threshold can be changed to your desired expiration alerting requirements.
type: STATIC
nrql:
  query: "FROM Metric SELECT floor((latest(nginx_ingress_controller_ssl_expire_time_seconds) - (aggregationendtime()/1000)) / (24*60*60)) FACET host WHERE instrumentation.name = 'remote-write'"

# Function used to aggregate the NRQL query value(s) for comparison to the terms.threshold (Default: SINGLE_VALUE)
valueFunction: SINGLE_VALUE

# List of Critical and Warning thresholds for the condition
terms:
  - priority: CRITICAL
    # Operator used to compare against the threshold.
    operator: BELOW
    # Value that triggers a violation
    threshold: 30
    # Time in seconds; 120 - 3600
    thresholdDuration: 300
    # How many data points must be in violation for the duration
    thresholdOccurrences: ALL

# Duration after which a violation automatically closes
# Time in seconds; 300 - 2592000 (Default: 86400 [1 day])
violationTimeLimitSeconds: 86400