id: 7c2d8e71-9f1d-472b-ad7f-8025c0059040
slug: github-dependabot

title: GitHub Dependabot

description: |+
  ## What is GitHub Dependabot?

  GitHub Dependabot helps you keep your dependencies up to date. Every day, it checks your dependency files for outdated requirements and opens individual PRs for any it finds. You review, merge, and get to work on the latest, most secure releases.

  ### Get started!

  Start ingesting Dependabot events by connecting GitHub to New Relic!

  Check out our GitHub Dependabot documentation to instrument your GitHub account to send Vulnerability events to New Relic's Vulnerability Management product.

  ### More info
  
  Check out the [documentation](https://docs.newrelic.com/docs/vulnerability-management/integrations/dependabot) to learn more about New Relic ingestion for GitHub Dependabot. 

summary: Ingest GitHub Dependabot events by connecting GitHub to New Relic
level: New Relic
authors:
  - New Relic
keywords:
  - vulnerability management
  - security
  - github
  - dependabot

documentation:
  - name: GitHub Dependabot integration installation docs
    description: Automatic integration for ingesting Dependabot vulnerabilities.
    url: >-
      https://docs.newrelic.com/docs/vulnerability-management/integrations/dependabot

installPlans:
  - github-dependabot-install
icon: logo.png
