id: 689827ca-e78b-4d30-989e-aa404a4f6984
slug: nginx-ingress-controller

title: NGINX Ingress Controller

description: |
  ## Why monitor the NGINX ingress controller? 

  The NGINX ingress controller exposes many useful metrics that can be scraped by a Prometheus server or agent. These metrics can inform you of ongoing process connections and the current ingress load that your system is handling. Furthermore, these metrics can inform you on ingress config reloads and empower alert conditions on config reload errors or unexpected config changes.

  ## NGINX ingress controller quickstart highlights

  - Config reload monitoring (errors and last successful reload)
  - Throughput faceted by ingress classes
  - Request/response insights on payload size and response time
  - CPU and memory statistics 

  ## Monitoring NGINX ingress controller

  The NGINX ingress controller has to have metrics enabled before they are available to be scraped. Instructions for ensuring your NGINX metrics are enabled can be found here: https://kubernetes.github.io/ingress-nginx/user-guide/monitoring/#wildcard-ingresses

summary: |
  Visualize NGINX ingress controller performance and alert on potential configuration errors. Download New Relic NGINX ingress controller quickstart to increase visibility into your ingress performance.

level: New Relic

authors:
  - New Relic

keywords:
  - kubernetes
  - k8s
  - nginx
  - ingress
  - controllers
  - config

installPlans:
  - third-party-nginx-ingress

# Documentation references
documentation:
  - name: NGINX Ingress Controller Quickstart
    url: https://kubernetes.github.io/ingress-nginx/deploy/#quick-start
    description: Details on installing the NGINX ingress controller in your Kubernetes cluster
  - name: Enabling metrics for your NGINX ingress controller
    url: https://kubernetes.github.io/ingress-nginx/user-guide/monitoring/#prometheus-and-grafana-installation-using-pod-annotations
    description: Details on enabling metrics for your NGINX ingress controller 

# Content / Design
icon: logo.svg
website: https://www.nginx.com/

dashboards:
  - nginx-ingress

alertPolicies:
  - nginx-ingress