id: 547c6b8a-ec5e-44e2-a1d2-0e3c3668aa40
slug: aws-security-hub
title: AWS Security Hub Integration
description: |+ 
  ## What is AWS Security Hub?

  Cloud security posture management service that performs security best practice checks, aggregates alerts, and enables automated remediation.
  
  ### Get started!
  
  Start ingesting AWS Security Hub events by connecting Amazon Web Services (AWS) security products to New Relic!
  
  Check out our AWS Security Hub documentation to instrument your account to send events and vulnerabilities to New Relic's Vulnerability Management product.
  
  ### More info
  
  Check out the [documentation](https://docs.newrelic.com/docs/vulnerability-management/integrations/aws) to learn more about New Relic ingestion for AWS Security Hub. 
summary: Ingest AWS Security Hub by connecting AWS to New Relic
icon: logo.png
level: New Relic
authors:
  - New Relic
documentation:
  - name: AWS Security Hub installation docs
    description: Cloud-based service for detecting vulnerabilities in AWS resources.
    url: >-
      https://docs.newrelic.com/docs/vulnerability-management/integrations/aws
installPlans: 
  - aws-security-hub-install
keywords:
  - aws
  - amazon web services
  - vulnerability management
  - security
