id: 52bd4e38-5f13-4b78-add8-d5c70bb34fba
slug: google-cloud-spanner-otel
description: |-
  ## What is Google Cloud Spanner?

  Google Cloud Spanner is a Globally-distributed relational database service built for the cloud. Add
  schemas, write and modify data, and run queries.

  ### How it works

  This quickstart works by using the [Prometheus OTel exporter](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/prometheusexporter) to send Spanner metrics to New Relic.

  ### Get started!
  
  The metric data available with this quickstart pairs alongside the [infrastructure monitoring quickstart](https://newrelic.com/instant-observability/google-cloud-spanner) for full stack observability on your cloud spanner intance. This integration focuses on Query metrics, Transaction metrics, and other DB monitoring metrics, while the infra integration focuses on monitoring the infrastructure.
  
  ### About this quickstart

  This integration gives you visibility into key metrics on your Spanner isntance. NOTE: The dashboard included in this quickstart works by using finding `instrumentation.source = gcpspanner.` If you want to use this without changing the queries, be sure to use this as the name to identify the data source. Here are some of the key metrics you can monitor with this integration:

  - Summary of active queries
  - Lock insights
  - Query details
  - Query insights
  - Transaction details
  - Transaction insights

summary: |-
  Leverage OTel to monitor GCP Cloud Spanner
icon: logo.svg
level: verified
authors:
  - New Relic
title: Google Cloud Spanner (OTel monitoring)
documentation:
  - name: Example Prometheus exporter
    description: |
      Example Google Cloud Spanner prometheus exporter
    url: >-
      https://github.com/architjugran/example-cloudspannerreceiver
  - name: Prometheus New Relic docs
    description: |
      Sending and identifying Prometheus data to New Relic
    url: >-
      https://docs.newrelic.com/docs/infrastructure/prometheus-integrations/get-started/send-prometheus-metric-data-new-relic/
keywords:
  - gcp
  - google cloud platform
  - database
  - newrelic-partner
  - otel

installPlans: 
  - cloud-spanner

dashboards: 
  - gcp-cloud-spanner
