# Name of the quickstart (required)
id: c9ac4abb-4a61-4eee-9e1e-79506806684e
slug: coredns

# Displayed in the UI (required)
title: CoreDNS Metrics

# Long-form description of the quickstart (required)
description: |
  The CoreDNS quickstart provides a dashboard and set of alerts that provides a holistic view of the CoreDNS instances in your environment from telemetry collected through Prometheus Remote Write.  This dashboard gives visibility into CoreDNS versions, status, request/response times, and cache statistics.

# Displayed in search results and recommendations. Summarizes a quickstarts functionality.
summary: |
  Easily install a curated dashboard and alerts to monitor the health of your CoreDNS instances.

# Support level: New Relic | Verified | Community (required)
level: Verified

# Authors of the quickstart (required)
authors:
  - New Relic
  - Brad Schmitt
  - Raga Potti

# Keywords for filtering / searching criteria in the UI
keywords:
  - coredns
  - prometheus
  - remote write
  - remote_write
  - remote-write
  - promql
  - grafana

documentation:
  - name: Prometheus installation docs
    description: |
      Use Prometheus remote_write or New Relic's Prometheus OpenMetrics integration
    url: https://docs.newrelic.com/docs/infrastructure/prometheus-integrations/install-configure-remote-write/set-your-prometheus-remote-write-integration/

alertPolicies:
  - coredns

installPlans:
  - setup-prometheus

# Content / Design
icon: coredns-logo.png

dashboards:
  - coredns
