name: High 400 Error Rate

description: |+
  This alert is triggered when a Traefik service has an HTTP 4xx error rate above 5% for over 5 minutes. This threshold should be adjusted to your own requirements.
type: STATIC
nrql:
  query: "FROM Metric 
   SELECT filter(
     sum(
       traefik_service_requests_total), 
     WHERE code Not RLIKE '4.*') * 100 
   / filter(
     sum(
       traefik_service_requests_total), WHERE code RLIKE '.*') 
   WHERE instrumentation.name = 'remote-write' FACET instance, service"

# Function used to aggregate the NRQL query value(s) for comparison to the terms.threshold (Default: SINGLE_VALUE)
valueFunction: SINGLE_VALUE

# List of Critical and Warning thresholds for the condition
terms:
  - priority: CRITICAL
    # Operator used to compare against the threshold.
    operator: BELOW
    # Value that triggers a violation
    threshold: 95
    # Time in seconds; 120 - 3600
    thresholdDuration: 300
    # How many data points must be in violation for the duration
    thresholdOccurrences: ALL

# Duration after which a violation automatically closes
# Time in seconds; 300 - 2592000 (Default: 86400 [1 day])
violationTimeLimitSeconds: 86400
