name: Too Many Open requests

description: |+
  This alert is triggered when a Traefik service has more than 50 open requests for over 1 minute. This threshold should be adjusted to your own requirements.
type: STATIC
nrql:
  query: "SELECT 
  if((average(traefik_service_open_connections) > 50), 
  average(traefik_service_open_connections), 1) 
  FROM Metric 
  WHERE instrumentation.name = 'remote-write' FACET instance, service"

# Function used to aggregate the NRQL query value(s) for comparison to the terms.threshold (Default: SINGLE_VALUE)
valueFunction: SINGLE_VALUE

# List of Critical and Warning thresholds for the condition
terms:
  - priority: CRITICAL
    # Operator used to compare against the threshold.
    operator: ABOVE
    # Value that triggers a violation
    threshold: 50
    # Time in seconds; 120 - 3600
    thresholdDuration: 60
    # How many data points must be in violation for the duration
    thresholdOccurrences: ALL

# Duration after which a violation automatically closes
# Time in seconds; 300 - 2592000 (Default: 86400 [1 day])
violationTimeLimitSeconds: 86400
