id: b48bf101-efdd-4723-b073-7dd58e291442


slug: apache-flink
description: |
  ## Comprehensive monitoring quickstart for Apache Flink
  New Relic detects your Apache Flink metrics like job manager (checkpoints, direct, mapped, metaspace memory usage),
  task manager (shuffle service, operators), heap memory usage and more.

  ## Why monitor Apache Flink?
  An ideal Apache Flink performance monitoring provides an easy way for effective monitoring and alerting of your Apache Flink jobs.


  ## What’s included in this quickstart?
  New Relic's Apache Flink monitoring quickstart boasts instant full-stack observability out-of-the-box:
  - High value alerts for your Apache Flink (errors, usage metrics and JVM).
  - Easy to use performance monitoring dashboards.
  - Custom alerts that proactively inform developers about the status of their Apache Flink jobs.


summary: |
  New Relic’s instant observability quickstart with Apache Flink monitoring helps to detect job manager, task manager, operators, shuffle service, logs and parses them into a JSON payload.
icon: logo.png
level: New Relic
authors:
  - New Relic
title: Apache Flink
documentation:
  - name: Apache Flink integration documentation
    description: |
      New Relic’s instant observability quickstart with Apache Flink monitoring helps to detect job manager, task manager, operators, shuffle service, logs and parses them into a JSON payload.
    url: >-
      https://docs.newrelic.com/docs/infrastructure/prometheus-integrations/install-configure-openmetrics/install-apache-flink/
      
keywords:
  - apache-flink
  - flink 
  - apache flink
  - data stream
installPlans:
  - apache-flink
dashboards:
  - apache-flink
alertPolicies:
  - apache-flink
