name: Redis down alert

description: |+
  This alert is triggered when the Redis instance is not responding for a continuous 5 minutes.

type: STATIC
nrql:
  query: "SELECT Sum(redis_up) FROM Metric where instrumentation.name='remote-write'"

# Function used to aggregate the NRQL query value(s) for comparison to the terms.threshold (Default: SINGLE_VALUE)
valueFunction: SINGLE_VALUE

# List of Critical and Warning thresholds for the condition
terms:
  - priority: CRITICAL
    # Operator used to compare against the threshold.
    operator: EQUALS
    # Value that triggers a violation
    threshold: 0
    # Time in seconds; 120 - 3600
    thresholdDuration: 300
    # How many data points must be in violation for the duration
    thresholdOccurrences: ALL

# Duration after which a violation automatically closes
# Time in seconds; 300 - 2592000 (Default: 86400 [1 day])
violationTimeLimitSeconds: 86400
