id: otel-jenkins-integration
displayName: Jenkins
description: |
  Jenkins is an open source automation server which enables developers around the world to reliably build, test, and deploy their software.
icon: logo.svg
install:
  primary:
    nerdlet:
      nerdletId: nr1-install-newrelic.quickstart-installation-plan
      nerdletState:
        quickstartId: 980ab07a-3483-4b44-bbac-ed9c0a9a41a1
      requiresAccount: true
  fallback:
    link:
      url: https://docs.newrelic.com/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/jenkins/monitoring-jenkins-ot/
keywords:
  - jenkins
  - opentelemetry
  - otel
  - pipelines
categoryTerms:
  - open source monitoring
