# Sets the URL name of the quickstart on public I/O (required)
slug: ext-linkerd

# Displayed in the UI (required)
title: Linkerd

# Long-form description of the quickstart (required)
description: |
  The Linkerd quickstart allows you to get visibility into the performance and available of your Linkerd service and dependencies. Use this quickstart together with the mock up integrations.
  \## Linkerd quickstart highlights
  The New Relic quickstart uses dashboards to proactively monitor your Linkerd services, like:
  - number of Requests
  - number of Responses
  - Response Latancy
  - Response Success Rate 
  \## Monitoring Linkerd
  This quickstart utilizes New Relic's ability to ingest Prometheus data (either from our OpenMetrics integration or via Prometheus remote write). See instructions for [sending Prometheus data to New Relic here](https://docs.newrelic.com/docs/infrastructure/prometheus-integrations/get-started/send-prometheus-metric-data-new-relic/).
  \### How do I configure my integration to scrape Linkerd services metrics?
  The approach to getting your Prometheus metrics into New Relic differs depending on which integration you use.
  \#### Prometheus Remote Write
  In addition to setting up your `remote_write` configuration as described [here](https://docs.newrelic.com/docs/infrastructure/prometheus-integrations/install-configure-remote-write/set-your-prometheus-remote-write-integration/) you MUST configure the data label as "Linkerd_Prometheus" (on step 1) to match the naming convention established in the Linkerd Entity in New Relic.
  Also you will have two options to add the Linkerd metrics to your prometheus:  
    1- When you install Linkerd you already have a prometheus running internally on your kubernetes cluster, you can add this endpoint to your prometheus.
    2- You can also get the metrics externally creating a service mapping to export the Linkerd metrics from the internal Prometheus installation, to an external Prometheus, by following the procedure in this link: https://linkerd.io/2.10/tasks/exporting-metrics/.
# Displayed in search results and recommendations. Summarizes a quickstarts functionality.
summary: |
  The Linkerd quickstart allows you to get visibility into the performance of your services.
# Support level: New Relic | Verified | Community (required)
level: Community

# Authors of the quickstart (required)
authors:
  - Dani Turco @Kinect-Consulting
  - Irvin Arias @Kinect-Consulting
  - Omar Castillo @Kinect-Consulting
  - David Perez @Kinect-Consulting

# Keywords for filtering / searching criteria in the UI
keywords:
  - Linkerd
  - Prometheus
  - remote-write

documentation:
  - name: Linkerd installation docs
    description: |
      The Linkerd quickstart allows you to get visibility into the performance of your instances.
    url: >-
      https://linkerd.io/2.10/getting-started/
installPlans:
  - third-party-ext-linkerd
# Allows us to construct reusable "install plans" and just use their ID in the quickstart config
alertPolicies:
  - ext-linkerd
dashboards:
  - ext-linkerd
# Content / Design
icon: logo.png
website: https://linkerd.io