id: 16dcca43-1a4f-4f94-8fd5-d05a085a99a3
slug: amazon-documentdb
title: Amazon DocumentDB
description: Fast, scalable, highly available, and fully managed document database service that supports MongoDB workloads.
summary: Monitor Amazon DocumentDB by connecting AWS to New Relic
level: New Relic
authors:
  - New Relic
keywords:
  - aws
  - amazon web services
  - database
documentation:
  - name: Amazon DocumentDB installation docs
    description: |
      Monitor Amazon DocumentDB by connecting AWS to New Relic.
    url: >-
      https://docs.newrelic.com/docs/integrations/amazon-integrations/aws-integrations-list/aws-documentdb-monitoring-integration
icon: logo.svg
installPlans:
  - aws-cloudwatch-metric-streams