id: 547a0d7c-e01c-4dab-ada7-c9dc5d2a3a71
# Name of the quickstart (required)
# sets the URL name of the quickstart on public I/O
slug: redis-prometheus

# Displayed in the UI (required)
title: Redis (Prometheus)

# Long-form description of the quickstart (required)
description: |+
  ## A complete Redis monitoring system

  Redis operates in-memory and achieves I/O faster than traditional database systems. It includes several data structures which make it ready to use right out of the box.

  New Relic provides a Redis quickstart which allows you to monitor your Redis instances out-of-the-box.

  ### New Relic - a perfect tool to monitor Redis using Prometheus.

  Redis is known for its speed, so ensuring that it stays operating at peak performance is paramount. Slowdowns can lead to a compromised user experience or even a complete application failure.

  Using the [New Relic Prometheus Remote-Write](https://docs.newrelic.com/docs/infrastructure/prometheus-integrations/install-configure-remote-write/set-your-prometheus-remote-write-integration/) integration you can deliver your critical Redis metrics from your internally supported instance of Prometheus directly to New Relic where the rest of your observability data resides.

  ### New Relic Redis quickstart features

  Our Redis quickstart include out-of-the-box dashboards and alerts, including data such as:
  - Overview Snapshot (# masters, # slaves) + charts with commands/sec and commands/sec by node
  - Charts showing connected clients, connected clients by node, changes since last save by node, expired keys/second by node, memory used by node, and blocked clients.
  - Charts showing keyspace hit ratio by node, evicted keys/second by node, input bytes/second by node, network I/O per second, and output bytes / second by node.

  ### Value of the Redis (Prometheus) quickstart

  The Redis (Prometheus) Quickstart provides a visual snapshot of all the key health information related to your Redis nodes and clusters. Monitoring is made easy via the clear, color-coded dashboard which showcases memory usage, network I/O, node health, and much more.

  ### Redis Prometheus Exporter (Kubernetes)

  If you are supporting Redis and Prometheus in a Kubernetes cluster, you can easily export Redis metrics to Prometheus using the [Prometheus Redis Exporter](https://github.com/prometheus-community/helm-charts/tree/main/charts/prometheus-redis-exporter).

summary: |
  New Relic provides crucial tools for monitoring your Redis instances using the [Prometheus Remote-Write](https://docs.newrelic.com/docs/infrastructure/prometheus-integrations/install-configure-remote-write/set-your-prometheus-remote-write-integration/) integraton. It supports features such as a visual dashboard complete with charts detailing all critical performance and health metrics relevant to your Redis system.


# Support level: New Relic | Verified | Community (required)
level: New Relic

# Authors of the quickstart (required)
authors:
  - New Relic

# Keywords for filtering / searching criteria in the UI
keywords:
  - redis
  - prometheus
  - remote
  - write
  - kubernetes
  - database

# Reference to install plans located under /install directory
# Allows us to construct reusable "install plans" and just use their ID in the quickstart config
installPlans:
  - setup-prometheus

# Documentation references
documentation:
  - name: Redis Prometheus Integration
    description: |
      Open source, key-value data structure store for use as a database, cache, and message broker with wide protocol and dataset support.
    url: https://docs.redis.com/latest/rs/administering/monitoring-metrics/prometheus-integration/

# Content / Design
icon: logo.png
website: https://redis.io/

dashboards:
  - redis-prometheus
  
alertPolicies:
  - redis-prometheus